version: '3'

services:
  robot-core:
    image: robot-wall-e
    build:
      context: .
    user: "root"
    env_file:
      - ${HOME}/Robot/Programme/configuration/.env
    devices:
      - "/dev/snd:/dev/snd" # périphériques audio
    volumes:
      - ${HOME}/Robot/Programme:${HOME}/Robot/Programme
    ports:
      - "8080:8080"