# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image-processing.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'image-processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image-processing.proto\x12\x37\x66r.roboteek.robot.services.visionartificielle.dto.image\"?\n\x16ImageProcessingRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x16\n\x0eprocessingType\x18\x02 \x01(\t\"G\n\x17ImageProcessingResponse\x12\x14\n\x0cjsonResponse\x18\x01 \x01(\t\x12\x16\n\x0eprocessingType\x18\x02 \x01(\t\"-\n\x0e\x41\x64\x64\x46\x61\x63\x65Request\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\"+\n\x0f\x41\x64\x64\x46\x61\x63\x65Response\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2\xeb\x02\n\x16ImageProcessingService\x12\xb1\x01\n\x0cprocessImage\x12O.fr.roboteek.robot.services.visionartificielle.dto.image.ImageProcessingRequest\x1aP.fr.roboteek.robot.services.visionartificielle.dto.image.ImageProcessingResponse\x12\x9c\x01\n\x07\x61\x64\x64\x46\x61\x63\x65\x12G.fr.roboteek.robot.services.visionartificielle.dto.image.AddFaceRequest\x1aH.fr.roboteek.robot.services.visionartificielle.dto.image.AddFaceResponseB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_IMAGEPROCESSINGREQUEST']._serialized_start=83
  _globals['_IMAGEPROCESSINGREQUEST']._serialized_end=146
  _globals['_IMAGEPROCESSINGRESPONSE']._serialized_start=148
  _globals['_IMAGEPROCESSINGRESPONSE']._serialized_end=219
  _globals['_ADDFACEREQUEST']._serialized_start=221
  _globals['_ADDFACEREQUEST']._serialized_end=266
  _globals['_ADDFACERESPONSE']._serialized_start=268
  _globals['_ADDFACERESPONSE']._serialized_end=311
  _globals['_IMAGEPROCESSINGSERVICE']._serialized_start=314
  _globals['_IMAGEPROCESSINGSERVICE']._serialized_end=677
# @@protoc_insertion_point(module_scope)
