# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import image_processing_pb2 as image__processing__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in image_processing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageProcessingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.processImage = channel.unary_unary(
                '/fr.roboteek.robot.services.visionartificielle.dto.image.ImageProcessingService/processImage',
                request_serializer=image__processing__pb2.ImageProcessingRequest.SerializeToString,
                response_deserializer=image__processing__pb2.ImageProcessingResponse.FromString,
                _registered_method=True)
        self.addFace = channel.unary_unary(
                '/fr.roboteek.robot.services.visionartificielle.dto.image.ImageProcessingService/addFace',
                request_serializer=image__processing__pb2.AddFaceRequest.SerializeToString,
                response_deserializer=image__processing__pb2.AddFaceResponse.FromString,
                _registered_method=True)


class ImageProcessingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def processImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'processImage': grpc.unary_unary_rpc_method_handler(
                    servicer.processImage,
                    request_deserializer=image__processing__pb2.ImageProcessingRequest.FromString,
                    response_serializer=image__processing__pb2.ImageProcessingResponse.SerializeToString,
            ),
            'addFace': grpc.unary_unary_rpc_method_handler(
                    servicer.addFace,
                    request_deserializer=image__processing__pb2.AddFaceRequest.FromString,
                    response_serializer=image__processing__pb2.AddFaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fr.roboteek.robot.services.visionartificielle.dto.image.ImageProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fr.roboteek.robot.services.visionartificielle.dto.image.ImageProcessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageProcessingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def processImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fr.roboteek.robot.services.visionartificielle.dto.image.ImageProcessingService/processImage',
            image__processing__pb2.ImageProcessingRequest.SerializeToString,
            image__processing__pb2.ImageProcessingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fr.roboteek.robot.services.visionartificielle.dto.image.ImageProcessingService/addFace',
            image__processing__pb2.AddFaceRequest.SerializeToString,
            image__processing__pb2.AddFaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
