syntax = "proto3";
option java_multiple_files = true;

package fr.roboteek.robot.services.visionartificielle.dto.image;

import "google/protobuf/empty.proto";

message ImageProcessingRequest {
  bytes image = 1;
  string processingType = 2;
}

message ImageProcessingResponse {
  string jsonResponse = 1;
  string processingType = 2;
}

message FaceRequest {
  string id = 1;
  string name = 2;
  bytes image = 3;
}

message FaceResponse {
  string id = 1;
  string name = 2;
}

message DeleteFaceRequest {
  string id = 1;
}

service ImageProcessingService {
  rpc processImage(ImageProcessingRequest) returns (ImageProcessingResponse);
  rpc addFace(FaceRequest) returns (FaceResponse);
  rpc updateFace(FaceRequest) returns (FaceResponse);
  rpc deleteFace(DeleteFaceRequest) returns (google.protobuf.Empty);
}
